### ISSUE TITLE
Bolt adapter fails for Neo4j 4.0

### ISSUE THREAD

**Issue by smackesey** [neo4jrb/activegraph#1589]
After upgrading my database to Neo4j 4.0, I can no longer connect with the bolt adapter (HTTP is working though). This code:

    adapter = Neo4j::Core::CypherSession::Adaptors::Bolt.new(MY_BOLT_URL, ssl: false)
    Neo4j::Core::CypherSession.new(adapter)

Gives this error:

    /Users/smackesey/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/neo4j-core-9.0.0/lib/neo4j/core/cypher_session/adaptors/bolt.rb:134:in `handshake': Couldn't agree on a version (Sent versions [1, 0, 0, 0]) (RuntimeError)

### Runtime information:

Neo4j database version: 4.0.0
`neo4j` gem version: 9.6.0
`neo4j-core` gem version: 9.0.0

**Comment by klobuczek** [comment]
@smackesey  Only activegraph versions >= 10.0.0.pre.alpha.11 support neo4j 4.0.0 (bolt and neo4j protocols only).

**Comment by smackesey** [comment]
@klobuczek I see... So is neo4j-core abandoned? I (and surely other users) don't use the model object (ActiveRecord-like) functionality, only the lower-level query interface provided by neo4j-core. Does activegraph provide a replacement for this?

Or better, is there some place I can go to read about the plans and state of the project? http://neo4jrb.io/ and the docs both appear to be out of date. Thanks

**Comment by architecture** [comment]
I think neo4j has abandoned the ruby language... I noticed the same thing. the gems and docs are no longer being maintained. I could not get the Core libs to work .... the db server has advanced by the gems have not....
