### ISSUE TITLE
How to update v9 migrations to v10 migrations?

### ISSUE THREAD

**Issue by mhanberg** [neo4jrb/activegraph#1602]
I am updating an app to use v10 to be able to use the seabolt adapter, and am running into a problem trying to deploy to a staging environment.

I think due to the rename, the current migrations are not being found because of the new label on the node.

Is this a bug or is there a way around this that I missed?

Thanks!

**Comment by jjg-dressipi** [comment]
@mhanberg : I've managed to get seabolt working with 9.6.2 as discussed [here](https://github.com/neo4jrb/activegraph/issues/1599), you may find that easier than updating to 10 (which is still alpha).  I find a 20-30% speed bump against http :smile:

**Comment by mhanberg** [comment]
@jjg-dressipi I tried to set that up, but I ran into an issue with indexes. `neo4j-core` uses a regex to parse out the labels, properties on the index, and it appears that it can't parse a multi-property index.

I don't have that problem when I use the v10 release.

This is the v10 code that works: https://github.com/neo4jrb/activegraph/blob/95f2f5dfbaa2abe3e86f7a87b387e98afd724004/lib/active_graph/core/schema.rb#L15

This neo4j-core code that v9 uses does not work: https://github.com/neo4jrb/neo4j-core/blob/4b649fca33a1b1dba8705e6f999764ad9fb4d76e/lib/neo4j/core/cypher_session/adaptors/schema.rb#L17

I also saw this problem when using the built-in bolt adapter that v9 provides (the bolt adapter and the "driver" adapter both use the v9 neo4j-core code I shared above)

**Comment by jjg-dressipi** [comment]
Ah, my schema doesn't seem to touch that issue, hence I get an easier ride ...

**Comment by mhanberg** [comment]
The index it chokes on is `- INDEX ON NODE:User(username, first_name, last_name)`

**Comment by amitsuryavanshi** [comment]
If you are migrating to v10 from v9, following migration should help,
`
class MigrateMigration < ActiveGraph::Migrations::Base
  def up
    execute('MATCH (n:`Neo4j::Migrations::SchemaMigration`) ' \
            'REMOVE n:`Neo4j::Migrations::SchemaMigration` ' \
            'SET n:`ActiveGraph::Migrations::SchemaMigration`')
  end

  def down
    raise ActiveGraph::IrreversibleMigration
  end
end
`

**Comment by mhanberg** [comment]
@amitsuryavanshi 

If I add this migration and run `bin/rails neo4j:migrate`, won't it still run the previous migrations that it doesn't think that it's run?

**Comment by mhanberg** [comment]
Should the migration runner look for the legacy migrations in addition so that this migration is not necessary?

**Comment by mhanberg** [comment]
I think I plan on going the v9.6.2 route and monkey patching the schema class from neo4j-core with the class from activegraph master (slightly modified to account for the difference in result classes).

That should hold us over until neo4j-core can be updated, or activegraph v10 is officially released. 

I attempted to contribute a patch for neo4j-core, but i don't have the time to invest in making sure it works with the versions of neo4j that neo4j-core supports.

@amitsuryavanshi Feel free to close this issue if you feel your answer is an acceptable resolution to this issue.
