### ISSUE TITLE
activegraph and MacOS < 10.15 compatibility

### ISSUE THREAD

**Issue by mstrofbass** [neo4jrb/activegraph#1610]
I was trying to upgrade to Neo4j 4.0 and first tried to upgrade to activegraph. When starting the rails server I got an error saying that [libseabolt](https://github.com/neo4j-drivers/seabolt) is required. 

I attempted to follow the instructions for installing the latest libseabolt release, but libseabolt requires openssl 1.0, which has been EOL'd in Homebrew and deleted.

So I tried to compile libseabolt from source using openssl 1.1.1, but libseabolt uses a function that's not available until MacOS 10.15.

As far as I can tell, the simplest solution is to build OpenSSL 1.0 from source. This seems like a lot of work to get a ruby gem to work, however. 

Is there some other option I am missing?

**Comment by klobuczek** [comment]
@mstrofbass have you tried using the prebuilt package https://github.com/neo4j-drivers/seabolt/releases ?

**Comment by mstrofbass** [comment]
@klobuczek yes, the pre-built packages are what require OpenSSL 1.0.

**Comment by klobuczek** [comment]
and this fails as well?
```
brew install michael-simons/homebrew-seabolt/seabolt
```

**Comment by mstrofbass** [comment]
No, that works fine and appears to fix the issue. Thanks

**Comment by klobuczek** [comment]
I admit the documentation is far from perfect but it is there https://github.com/neo4jrb/neo4j-ruby-driver/blob/master/README.md

**Comment by mstrofbass** [comment]
I think adding this to the upgrade guide on the read the docs site would be beneficial.
