### ISSUE TITLE
Relational query in wrong order

### ISSUE THREAD

**Issue by shu-bc** [neo4jrb/activegraph#1611]
Suppose a book model `has_many` pages like this
```ruby
class Book
  has_many :out, :pages, type: :has, model_class: :Page
end
```
`book.page_ids`  can return an array of unique ids of related pages instances
`book.page_ids = [....]; book.save`  is supposed to update its relation, as it does in v9.x.

But in v10.0, this doesn't work, since it will issue delete queries that delete existing relation only **AFTER** issuing create queries.
This causes trouble if some id in the array is included in the existing relations.
In an extreme case, if you pass the exact same id array, then this will completely destroy existing relations.

This can be solved by just reversing the order of relational queries.

Additional information which could be helpful if relevant to your issue:

### Runtime information:

Neo4j database version: neo4j 3.4.0
`neo4j` gem version: v10.0
`neo4j-core` gem version:

**Comment by klobuczek** [comment]
@shu-bc it would be always helpful to have a complete spec. Are you saying that this spec will fail?
```
it 'does not delete pages on reassignment` do
  page = Page.create
  book = Book.create(pages: page)
  book.page_ids = [page.id]
  book.save
  expect(book.pages).to be_present
end
```

**Comment by amitsuryavanshi** [comment]
Confirming that, this is a issue. If you have a non integer `id_property` you get this issue. Thanks for reporting @shu-bc, we are on it.

**Comment by shu-bc** [comment]
@klobuczek yes, exactly.

@amitsuryavanshi oh yes, that is the case. Our is id is created by SecureRandom.uuid
