### ISSUE TITLE
Version 11 betas packaged for java?

### ISSUE THREAD

**Issue by jec** [neo4jrb/activegraph#1628]
It appears that the v11 betas are packaged for java, including this one:

https://rubygems.org/gems/activegraph/versions/11.0.0.beta.3-java

I've included it in my Gemfile:

```ruby
gem 'activegraph', '~> 11.0.0.beta.3'
```

And I get this error:

> Could not find gem 'activegraph (~> 11.0.0.beta.3)' in any of the gem sources listed in your Gemfile.

I'm assuming this version is required for Neo4j 4.1. Will these be packaged for standard Ruby soon?

**Comment by K-Lovelace** [comment]
Hi, i'm also very interested in activegraph supporting Neo4j 4.1. Does anyone knows when a supporting version will be available ?

**Comment by klobuczek** [comment]
@jec that's right. For now, activegraph 11 beta versions require JRuby. That's not likely to change soon. We need 4.1 driver to support neo4j 4.1. So far we have the driver on jRuby only. I'm still discussing with neo4j if they could expose some components of the go driver as c libraries. WIthout that the only other option would be a pure ruby driver and that's a lot of work. Your options are switching to JRuby on neo4j 4.1 or staying on 4.0 for a while.

**Comment by K-Lovelace** [comment]
Is Neo4j 4.0.8 fully supported by version 10 (as in production-ready) ? Anything special we should check before upgrading our production ? It might keep us going while waiting for Neo4j 4.1 support.

**Comment by klobuczek** [comment]
Neo4j 4.0.x is fully supported to the extent of driver 1.7 support. (https://neo4j.com/docs/driver-manual/1.7/)
That means for example no multi-database access. activegraph 10 and driver 1.7 is used in production with neo4j 4.0.6 on a large commercial project.

**Comment by jec** [comment]
@klobuczek Thanks for the info.

**Comment by innoc** [comment]
@klobuczek Is activegraph 11 still only compatible with Jruby?
