### ISSUE TITLE
How to specify a database in Rails

### ISSUE THREAD

**Issue by jec** [neo4jrb/activegraph#1629]
I'm using ActiveGraph 10.0.1 and Neo4j 4.0.6 Enterprise, and I've been experimenting with multi-database features. However, I haven't figured out how to connect to a specific database from Rails. I haven't found any documentation about it, and so I've tried as many permutations as I can think of. Is it possible to connect to a database other than the default?

**Comment by klobuczek** [comment]
Driver 1.7 (used in activegraph 10) supports accessing the default database only (which can be specified in neo4j.conf). For accessing different databases per session the minimum driver version is 4.0. Currently, driver 4.1.beta is available for JRuby only and compatible with activegraph 11 beta.
