### ISSUE TITLE
General Cypher Support

### ISSUE THREAD

**Issue by ShalokShalom** [neo4jrb/activegraph#1672]
Does activegraph support Cypher in general or really only Neo4j?

I am interested in Ruby and https://age.apache.org and fail to see, how neo4jrb would only support neo4j, when Cypher is a standard and used like that in other projects too?

So far as I can see, would this attract new users and by so, new developers. 

Thanks a lot

**Comment by klobuczek** [comment]
activegraph supports what neo4j-ruby-driver supports which in turn supports what the official neo4j drivers support. We have no ambition to support anything beyond that. This question should be addressed to neo4j.
