### ISSUE TITLE
Installation Instructions Are Not Working

### ISSUE THREAD

**Issue by scarrick68** [neo4jrb/activegraph#1678]
I'm trying to follow the installation instructions, but I keep getting this error:

`Could not open library 'libseabolt17.dylib': dlopen(libseabolt17.dylib, 0x0005): tried: 'libseabolt17.dylib' (no such file), '/usr/local/lib/libseabolt17.dylib' (no such file), '/usr/lib/libseabolt17.dylib' (no such file),`

I'm guessing this driver is supposed to come with a neo4j installation? I'm running it in a container and maybe the rails app can't see the driver?

Homebrew only has version 5.1 available, so mac users may need to install manually.

This error happens even when trying to bootstrap a new app with 
`rails new myapp -O -m https://raw.githubusercontent.com/neo4jrb/activegraph/master/docs/activegraph.rb`

It also happens when trying to use a rake task to install or setup neo4j.
`rake neo4j:install`

The example install task provided in the docs results in:
`rake neo4j:install[community-4.0.6]
=> no matches found: neo4j:install[community-4.0.6]`

Unrelated, but the official neo4j ruby app template 404s `rails new asset_portal -m http://neo4jrb.io/neo4j/neo4j.rb -O`

Additional information which could be helpful if relevant to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 
`neo4j-core` gem version:

**Comment by robin850** [comment]
I had the same problem using out-dated versions of the `activegraph` and `neo4j-ruby-driver` gems. It looks like previous versions required the installation of [a Bolt driver](https://github.com/neo4j-drivers/seabolt) that is no longer maintained.

The following is working for me (with Ruby 3.2.1) :

~~~ruby
gem 'activegraph', '~> 11.3'
gem 'neo4j-ruby-driver', '~> 4.4.3'
~~~

**Comment by amitsuryavanshi** [comment]
Closing this as older versions are not supported. Newer versions work fine.
