### ISSUE TITLE
Need update for Neo4j 5.X

### ISSUE THREAD

**Issue by jeffkirk1** [neo4jrb/activegraph#1679]
HI there,

It appears that the current release of this gem is incompatible with Neo4J 5.X. I attempted to use it with a newer Neo4J instance, and ran into the same error reported by another user:

`Java::OrgNeo4jDriverExceptions::ClientException: There is no procedure with the name `db.indexes` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`

I am able to connect to my older Neo4J 4.4.12 instance using Neo4j Desktop without an errors with the same code. Currently using the following: 

Ruby on Rails 6.1.6.1
JRuby 9.3.6.0 (CRuby 2.6.8 equivalent)
activegraph 11.0.2 java
neo4j-java-driver 4.4.0 java
neo4j-rake_tasks (0.7.19)

**Comment by klobuczek** [comment]
Fixed in 11.1.0
