### ISSUE TITLE
There is no procedure with the name db.indexes registered for this database instance.

### ISSUE THREAD

**Issue by himberjack** [neo4jrb/activegraph#1680]
I have installed activegraph 11 and neo4j driver 4.4.0 beta 1. I am getting the following: 

`GraphAsset.last BOLT: 132ms /Users/a/.rvm/gems/ruby-3.1.2/gems/neo4j-ruby-driver-4.4.0.beta.1/ruby/neo4j/driver/internal/util/result_holder.rb:38:in result!': There is no procedure with the name db.indexes registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed. (Neo4j::Driver::Exceptions::ClientException)
`

But I am able to successfully query: `ActiveGraph::Base.query('MATCH (n) RETURN n LIMIT $limit', limit: 10).entries.length CYPHER MATCH (n) RETURN n LIMIT $limit | {:limit=>10} BOLT: 73ms => 4`
I am working against AuraDB hosted by neo4j

**Comment by klobuczek** [comment]
Fixed in 11.1.0
