### ISSUE TITLE
Ruby setup doesn't work

### ISSUE THREAD

**Issue by nomasprime** [neo4jrb/activegraph#1689]
Running the docs doesn't work.

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)

https://neo4j.com/developer/ruby-course/

`rails new asset_portal -m http://neo4jrb.io/neo4j/neo4j.rb -O`

`404 Not Found (OpenURI::HTTPError)`

### Runtime information:

Neo4j database version: 
`neo4j` gem version: 
`neo4j-core` gem version:

**Comment by amitsuryavanshi** [comment]
@nomasprime Can you check if this works https://neo4jrb.readthedocs.io/en/stable/Setup.html ?

**Comment by nomasprime** [comment]
Ah, I should have noticed I was on an old version 🤦‍♂️ Brilliant! Thanks @amitsuryavanshi 👊
