### ISSUE TITLE
Is it possible to pass username and password via `NEO4J_URL` env var

### ISSUE THREAD

**Issue by jhulme-ut** [neo4jrb/activegraph#1701]
Hi,

I'm in the process of upgrading from 9.6.2 to 11.4.0.
In 9.6.2 we just used the `NEO4J_URL` env var with the format `<scheme>://<username>:<password>@<db_url>` and it worked fine.

Now with the same url in 11.4.0 auth does not work
Adding logging around the config in [railtie.rb](https://github.com/neo4jrb/activegraph/blob/master/lib/active_graph/railtie.rb#L69) I was able to see that we are username and password are both blank and we are getting `Neo4j::Driver::AuthTokens.none` for the auth token.

When I set `config.neo4j.driver.username` and `config.neo4j.driver.password` and took them out of `NEO4J_URL` it worked and I was able to connect.  

It's just annoying that it seems we can't connect with a single env var anymore. Is there a way to do it?

### Runtime information:

Neo4j database version: 4.0.8
`activegraph` gem version: 11.4.0
`neo4j-ruby-driver` gem version: 4.4.4

**Comment by klobuczek** [comment]
I think we should add the possibility to configure everything via env vars. But I don't think it will be 1 var including all. username and password will have to be separate variables as the notation `<scheme>://<username>:<password>@<db_url>` is not used by the server or other language drivers anymore.

**Comment by klobuczek** [comment]
If you were willing to provide a PR translating all variables prefixed with `NEO4J_` into configuration options with the same convention the neo4j server does https://neo4j.com/docs/operations-manual/current/docker/configuration/#docker-environment-variables it would be great.
